export * from './BasketballSvg';
export * from './PaperPlaneSvg';
export * from './RollsRoyceSvg';
export * from './SkateboardSvg';
export * from './FighterPlaneSvg';
export * from './SunSvg';
export * from './LeftHandSvg';
export * from './RightHandSvg';
export * from './StartSvg';
