export { BasketballSvg } from './BasketballSvg';
export { PaperPlaneSvg } from './PaperPlaneSvg';
export { RollsRoyceSvg } from './RollsRoyceSvg';
export { SkateboardSvg } from './SkateboardSvg';
export { FighterPlaneSvg } from './FighterPlaneSvg';
export { SunSvg } from './SunSvg';
export { LeftHandSvg } from './LeftHandSvg';
export { RightHandSvg } from './RightHandSvg';
export { StartSvg } from './StartSvg';
