// Component exports
export { AppHeader } from './AppHeader'
export { AppBackground } from './AppBackground'
export { WelcomeScreen } from './WelcomeScreen'
export { ScreenCaptureModal } from './ScreenCaptureModal'
export { ScrollToTopButton } from './ScrollToTopButton'
export { FormattedOutput } from './FormattedOutput'
export { SmartMessage } from './SmartMessage'
export { FormattingDemo } from './FormattingDemo'
export { TestFormatting } from './TestFormatting'
