import type { AIModel } from './types';

export const anthropicModels: AIModel[] = [
  {
    id: 'claude-3-5-sonnet',
    name: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet',
    provider: 'anthropic',
    description: 'Anthropic\'s most capable model for complex tasks',
    category: 'reasoning',
    maxTokens: 8192,
    inputCost: 3.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'advanced-reasoning', 'code-generation'],
    contextWindow: 200000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'claude-sonnet-4-5-20250929',
    name: 'claude-sonnet-4-5-20250929',
    displayName: 'Claude Sonnet 4.5 2025-09-29',
    provider: 'anthropic',
    description: 'Anthropic\'s latest model',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.8,
    isReasoning: false,
  },
  {
    id: 'claude-haiku-4-5',
    name: 'claude-haiku-4-5',
    displayName: 'Claude Haiku 4.5',
    provider: 'anthropic',
    description: 'Anthropic\'s latest model',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
  },
  {
    id: 'claude-sonnet-4-20250514',
    name: 'claude-sonnet-4-20250514',
    displayName: 'Claude Sonnet 4 2025-05-14',
    provider: 'anthropic',
    description: 'Anthropic\'s latest model',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
  },
];
