import type { AIModel } from './types';

export const cerebrasModels: AIModel[] = [
  {
    id: 'cerebras/zai-glm-4.6',
    name: 'zai-glm-4.6',
    displayName: 'Zai GLM 4.6 (Cerebras)',
    provider: 'cerebras',
    description: 'Cerebras Zai GLM 4.6 model',
    category: 'text',
    maxTokens: 40960,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'qwen-3-32b',
    name: 'qwen-3-32b',
    displayName: 'Qwen 3 32B (Cerebras)',
    provider: 'cerebras',
    description: 'Cerebras Qwen 3 32B model',
    category: 'text',
    maxTokens: 32000,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
];
