import type { AIModel } from './types';

export const deepseekModels: AIModel[] = [
  {
    id: 'deepseek/deepseek-chat',
    name: 'deepseek-chat',
    displayName: 'DeepSeek Chat',
    provider: 'deepseek',
    description: 'DeepSeek-V3.2-Exp (Non-thinking Mode)',
    category: 'text',
    maxTokens: 4096,
    inputCost: 0.28,
    outputCost: 0.42,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation', 'json-output', 'function-calling'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'deepseek/deepseek-reasoner',
    name: 'deepseek-reasoner',
    displayName: 'DeepSeek Reasoner',
    provider: 'deepseek',
    description: 'DeepSeek-V3.2-Exp (Thinking Mode)',
    category: 'reasoning',
    maxTokens: 32000,
    inputCost: 0.28,
    outputCost: 0.42,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation', 'json-output', 'advanced-reasoning'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
];
