import type { AIModel } from './types';

export const falModels: AIModel[] = [
  {
    id: 'fal-flux-schnell',
    name: 'fal-ai/flux/schnell',
    displayName: 'FLUX Schnell (fal)',
    provider: 'fal',
    description: 'Ultra-fast FLUX image generation via fal.ai',
    category: 'image-generation',
    maxTokens: 0,
    inputCost: 0.003,
    outputCost: 0.003,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['image-generation'],
    contextWindow: 0,
    isAvailable: true,
    temperature: undefined,
    isReasoning: false,
  },
  {
    id: 'fal-flux-dev',
    name: 'fal-ai/flux/dev',
    displayName: 'FLUX Dev (fal)',
    provider: 'fal',
    description: 'High-quality FLUX development model via fal.ai',
    category: 'image-generation',
    maxTokens: 0,
    inputCost: 0.005,
    outputCost: 0.005,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['image-generation'],
    contextWindow: 0,
    isAvailable: true,
    temperature: undefined,
    isReasoning: false,
  },
  {
    id: 'fal-flux-pro',
    name: 'fal-ai/flux-pro/v1.1',
    displayName: 'FLUX Pro (fal)',
    provider: 'fal',
    description: 'Professional-grade FLUX image generation via fal.ai',
    category: 'image-generation',
    maxTokens: 0,
    inputCost: 0.01,
    outputCost: 0.01,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['image-generation'],
    contextWindow: 0,
    isAvailable: true,
    temperature: undefined,
    isReasoning: false,
  },
  {
    id: 'fal-nano-banana-2',
    name: 'fal-ai/nano-banana-2',
    displayName: 'Nano Banana 2 (fal)',
    provider: 'fal',
    description: 'Fast, high-quality image generation via fal.ai',
    category: 'image-generation',
    maxTokens: 0,
    inputCost: 0.008,
    outputCost: 0.008,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['image-generation'],
    contextWindow: 0,
    isAvailable: true,
    temperature: undefined,
    isReasoning: false,
  },
  {
    id: 'fal-kling-v2',
    name: 'fal-ai/kling-video/v2/master/text-to-video',
    displayName: 'Kling 2.0 Master (fal)',
    provider: 'fal',
    description: 'Cinematic text-to-video generation via fal.ai',
    category: 'video-generation',
    maxTokens: 0,
    inputCost: 0.05,
    outputCost: 0.05,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: true,
    capabilities: ['video-generation'],
    contextWindow: 0,
    isAvailable: true,
    temperature: undefined,
    isReasoning: false,
  },
  {
    id: 'fal-minimax-video',
    name: 'fal-ai/minimax/video-01',
    displayName: 'MiniMax Video (fal)',
    provider: 'fal',
    description: 'High-quality text-to-video via fal.ai',
    category: 'video-generation',
    maxTokens: 0,
    inputCost: 0.04,
    outputCost: 0.04,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: true,
    capabilities: ['video-generation'],
    contextWindow: 0,
    isAvailable: true,
    temperature: undefined,
    isReasoning: false,
  },
];
