import type { AIModel } from './types';

export const googleModels: AIModel[] = [
  {
    id: 'models/gemini-2.5-flash-native-audio-preview-12-2025',
    name: 'gemini-2.5-flash-native-audio-preview-12-2025',
    displayName: 'Gemini 2.5 Flash Native Audio Preview',
    provider: 'google',
    description: 'Gemini 2.5 Flash Native Audio Preview',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-2.5-pro',
    name: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    provider: 'google',
    description: 'Gemini 2.5 Pro',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'code-generation'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-2.0-flash-exp',
    name: 'gemini-2.0-flash-exp',
    displayName: 'Gemini 2.0 Flash (Experimental)',
    provider: 'google',
    description: 'Latest experimental Gemini model with improved performance',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'code-generation'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-1.5-flash',
    name: 'gemini-1.5-flash',
    displayName: 'Gemini 1.5 Flash',
    provider: 'google',
    description: 'Fast and efficient multimodal model',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-1.5-pro',
    name: 'gemini-1.5-pro',
    displayName: 'Gemini 1.5 Pro',
    provider: 'google',
    description: 'Most capable multimodal model for complex reasoning',
    category: 'reasoning',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'advanced-reasoning'],
    contextWindow: 2000000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'models/gemini-2.5-flash-image',
    name: 'nano banana',
    displayName: 'Nano Banana',
    provider: 'google',
    description: 'Advanced flash model with enhanced capabilities',
    category: 'image-generation',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images'],
    contextWindow: 32000,
    isAvailable: true,
    temperature: 0.8,
    isReasoning: false,
  },
  {
    id: 'models/gemini-flash-latest',
    name: 'gemini-flash-latest',
    displayName: 'Gemini Flash Latest',
    provider: 'google',
    description: 'Latest Gemini flash model',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images'],
    contextWindow: 32000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-flash-lite-latest',
    name: 'gemini-flash-lite-latest',
    displayName: 'Gemini Flash Lite Latest',
    provider: 'google',
    description: 'Latest Gemini flash lite model',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images'],
    contextWindow: 32000,
    isAvailable: true,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    provider: 'google',
    description: 'Advanced flash model with enhanced capabilities',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'code-generation'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-3-flash-preview',
    name: 'gemini-3-flash-preview',
    displayName: 'Gemini 3 Flash Preview',
    provider: 'google',
    description: 'Latest Gemini 3 flash model',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: false,
    capabilities: ['text', 'images', 'audio'],
    contextWindow: 32000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
];
