import type { AIModel } from './types';

export const googleModels: AIModel[] = [
  {
    id: 'gemini-3.5-flash',
    name: 'gemini-3.5-flash',
    displayName: 'Gemini 3.5 Flash',
    provider: 'google',
    description: 'Gemini 3.5 Flash',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-3.1-flash-lite',
    name: 'gemini-3.1-flash-lite',
    displayName: 'Gemini 3.1 Flash Lite',
    provider: 'google',
    description: 'Gemini 3.1 Flash Lite',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-2.5-flash-native-audio-preview-12-2025',
    name: 'gemini-2.5-flash-native-audio-preview-12-2025',
    displayName: 'Gemini 2.5 Flash Native Audio Preview',
    provider: 'google',
    description: 'Gemini 2.5 Flash Native Audio Preview',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-2.5-flash-image',
    name: 'gemini-2.5-flash-image',
    displayName: 'Gemini 2.5 Flash Image',
    provider: 'google',
    description: 'Gemini 2.5 Flash Image',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-3-pro-preview',
    name: 'gemini-3-pro-preview',
    displayName: 'Gemini 3 Pro Preview',
    provider: 'google',
    description: 'Gemini 3 Pro Preview',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-flash-latest',
    name: 'gemini-flash-latest',
    displayName: 'Gemini Flash Latest',
    provider: 'google',
    description: 'Gemini Flash Latest',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-2.5-pro',
    name: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    provider: 'google',
    description: 'Gemini 2.5 Pro',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'code-generation'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'gemini-flash-lite-latest',
    name: 'gemini-flash-lite-latest',
    displayName: 'Gemini Flash Lite Latest',
    provider: 'google',
    description: 'Gemini Flash Lite Latest',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-2.5-flash-image',
    name: 'nano banana',
    displayName: 'Nano Banana',
    provider: 'google',
    description: 'Advanced flash model with enhanced capabilities',
    category: 'image-generation',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images'],
    contextWindow: 32000,
    isAvailable: true,
    temperature: 0.8,
    isReasoning: false,
  },


  {
    id: 'gemini-2.5-flash',
    name: 'gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    provider: 'google',
    description: 'Advanced flash model with enhanced capabilities',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'code-generation'],
    contextWindow: 1000000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
  {
    id: 'models/gemini-3-flash-preview',
    name: 'gemini-3-flash-preview',
    displayName: 'Gemini 3 Flash Preview',
    provider: 'google',
    description: 'Latest Gemini 3 flash model',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: false,
    capabilities: ['text', 'images', 'audio'],
    contextWindow: 32000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: false,
  },
];
