import type { AIModel } from './types';

/**
 * Groq production + preview models (June 2026).
 * @see https://console.groq.com/docs/models
 * @see https://console.groq.com/docs/deprecations
 */
export const groqModels: AIModel[] = [
  {
    id: 'openai/gpt-oss-120b',
    name: 'openai/gpt-oss-120b',
    displayName: 'GPT OSS 120B',
    provider: 'groq',
    description: 'OpenAI flagship open-weight model with reasoning and tool use',
    category: 'reasoning',
    maxTokens: 65536,
    inputCost: 0.15,
    outputCost: 0.60,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling', 'reasoning'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 1.0,
    isReasoning: true,
  },
  {
    id: 'openai/gpt-oss-20b',
    name: 'openai/gpt-oss-20b',
    displayName: 'GPT OSS 20B',
    provider: 'groq',
    description: 'Fast open-weight model with reasoning — highest Groq throughput',
    category: 'reasoning',
    maxTokens: 65536,
    inputCost: 0.075,
    outputCost: 0.30,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling', 'reasoning'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 1.0,
    isReasoning: true,
  },
  {
    id: 'llama-3.3-70b-versatile',
    name: 'llama-3.3-70b-versatile',
    displayName: 'Llama 3.3 70B Versatile',
    provider: 'groq',
    description: 'Meta Llama 3.3 70B — strong general-purpose model on Groq',
    category: 'text',
    maxTokens: 32768,
    inputCost: 0.59,
    outputCost: 0.79,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling', 'reasoning'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'llama-3.1-8b-instant',
    name: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B Instant',
    provider: 'groq',
    description: 'Ultra-fast small model for quick responses',
    category: 'text',
    maxTokens: 131072,
    inputCost: 0.05,
    outputCost: 0.08,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'qwen/qwen3-32b',
    name: 'qwen/qwen3-32b',
    displayName: 'Qwen3 32B',
    provider: 'groq',
    description: 'Alibaba Qwen3 reasoning model (preview)',
    category: 'reasoning',
    maxTokens: 40960,
    inputCost: 0.29,
    outputCost: 0.59,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'reasoning', 'function-calling'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: true,
  },
  {
    id: 'meta-llama/llama-4-scout-17b-16e-instruct',
    name: 'meta-llama/llama-4-scout-17b-16e-instruct',
    displayName: 'Llama 4 Scout 17B',
    provider: 'groq',
    description: 'Meta Llama 4 Scout with vision and multimodal support (preview)',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.11,
    outputCost: 0.34,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'vision'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
];

/** Maps retired Groq model IDs to current replacements. */
export const GROQ_MODEL_MIGRATIONS: Record<string, string> = {
  'mixtral-8x7b-32768': 'llama-3.3-70b-versatile',
  'gemma2-9b-it': 'llama-3.1-8b-instant',
  'deepseek-r1-distill-llama-70b': 'openai/gpt-oss-120b',
  'qwen-qwq-32b': 'qwen/qwen3-32b',
  'llama-3.2-90b-vision-preview': 'meta-llama/llama-4-scout-17b-16e-instruct',
  'llama-3.2-11b-vision-preview': 'meta-llama/llama-4-scout-17b-16e-instruct',
};
