import type { AIModel } from './types';

export const groqModels: AIModel[] = [
  {
    id: 'openai/gpt-oss-120b',
    name: 'openai/gpt-oss-120b',
    displayName: 'GPT OSS 120B',
    provider: 'groq',
    description: 'Open source GPT-style model with 120B parameters running on Groq',
    category: 'reasoning',
    maxTokens: 8192,
    inputCost: 0.00,
    outputCost: 0.00,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling', 'reasoning'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 1.0,
    isReasoning: true,
  },
  {
    id: 'llama-3.3-70b-versatile',
    name: 'llama-3.3-70b-versatile',
    displayName: 'Llama 3.3 70B Versatile',
    provider: 'groq',
    description: 'Meta\'s Llama 3.3 70B model optimized for versatile tasks',
    category: 'text',
    maxTokens: 8192,
    inputCost: 0.59,
    outputCost: 0.79,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling', 'reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'llama-3.1-8b-instant',
    name: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B Instant',
    provider: 'groq',
    description: 'Fast and efficient Llama 3.1 8B model for quick responses',
    category: 'text',
    maxTokens: 8192,
    inputCost: 0.05,
    outputCost: 0.08,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'llama-3.2-90b-vision-preview',
    name: 'llama-3.2-90b-vision-preview',
    displayName: 'Llama 3.2 90B Vision',
    provider: 'groq',
    description: 'Llama 3.2 with vision capabilities for image understanding',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.90,
    outputCost: 0.90,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'vision'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'llama-3.2-11b-vision-preview',
    name: 'llama-3.2-11b-vision-preview',
    displayName: 'Llama 3.2 11B Vision',
    provider: 'groq',
    description: 'Compact Llama 3.2 with vision capabilities',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 0.18,
    outputCost: 0.18,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'vision'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'mixtral-8x7b-32768',
    name: 'mixtral-8x7b-32768',
    displayName: 'Mixtral 8x7B',
    provider: 'groq',
    description: 'Mistral\'s MoE model with 8 experts, great for diverse tasks',
    category: 'text',
    maxTokens: 32768,
    inputCost: 0.24,
    outputCost: 0.24,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling', 'coding'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'gemma2-9b-it',
    name: 'gemma2-9b-it',
    displayName: 'Gemma 2 9B',
    provider: 'groq',
    description: 'Google\'s Gemma 2 instruction-tuned model',
    category: 'text',
    maxTokens: 8192,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'function-calling'],
    contextWindow: 8192,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'deepseek-r1-distill-llama-70b',
    displayName: 'DeepSeek R1 Distill Llama 70B',
    provider: 'groq',
    description: 'DeepSeek R1 reasoning model distilled into Llama 70B',
    category: 'reasoning',
    maxTokens: 8192,
    inputCost: 0.59,
    outputCost: 0.79,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'reasoning', 'function-calling'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: true,
  },
  {
    id: 'qwen-qwq-32b',
    name: 'qwen-qwq-32b',
    displayName: 'Qwen QWQ 32B',
    provider: 'groq',
    description: 'Alibaba\'s Qwen reasoning model',
    category: 'reasoning',
    maxTokens: 8192,
    inputCost: 0.29,
    outputCost: 0.39,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'reasoning', 'function-calling'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.6,
    isReasoning: true,
  },
];
