import type { AIModel } from './types';

export const openrouterModels: AIModel[] = [
  {
    id: 'openrouter/anthropic/claude-3.5-sonnet',
    name: 'anthropic/claude-3.5-sonnet',
    displayName: 'Claude 3.5 Sonnet (OpenRouter)',
    provider: 'openrouter',
    description: 'Claude 3.5 Sonnet via OpenRouter',
    category: 'reasoning',
    maxTokens: 8192,
    inputCost: 3.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'advanced-reasoning', 'code-generation'],
    contextWindow: 200000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'openrouter/openai/gpt-4o',
    name: 'openai/gpt-4o',
    displayName: 'GPT-4o (OpenRouter)',
    provider: 'openrouter',
    description: 'GPT-4o via OpenRouter',
    category: 'multimodal',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: false,
    capabilities: ['text', 'images', 'audio', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'openrouter/google/gemini-pro-1.5',
    name: 'google/gemini-pro-1.5',
    displayName: 'Gemini Pro 1.5 (OpenRouter)',
    provider: 'openrouter',
    description: 'Gemini Pro 1.5 via OpenRouter',
    category: 'multimodal',
    maxTokens: 8192,
    inputCost: 3.50,
    outputCost: 10.50,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: true,
    capabilities: ['text', 'images', 'audio', 'video', 'function-calling', 'advanced-reasoning'],
    contextWindow: 2000000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'openrouter/meta-llama/llama-3.1-405b-instruct',
    name: 'meta-llama/llama-3.1-405b-instruct',
    displayName: 'Llama 3.1 405B Instruct (OpenRouter)',
    provider: 'openrouter',
    description: 'Meta Llama 3.1 405B via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 2.65,
    outputCost: 3.18,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'openrouter/meta-llama/llama-3.1-70b-instruct',
    name: 'meta-llama/llama-3.1-70b-instruct',
    displayName: 'Llama 3.1 70B Instruct (OpenRouter)',
    provider: 'openrouter',
    description: 'Meta Llama 3.1 70B via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.90,
    outputCost: 0.90,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'openrouter/mistralai/mistral-7b-instruct',
    name: 'mistralai/mistral-7b-instruct',
    displayName: 'Mistral 7B Instruct (OpenRouter)',
    provider: 'openrouter',
    description: 'Mistral 7B Instruct via OpenRouter',
    category: 'text',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: false,
  },
  {
    id: 'openrouter/teknium/openhermes-2.5-mistral-7b',
    name: 'teknium/openhermes-2.5-mistral-7b',
    displayName: 'OpenHermes 2.5 Mistral 7B (OpenRouter)',
    provider: 'openrouter',
    description: 'OpenHermes 2.5 Mistral 7B via OpenRouter',
    category: 'text',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: false,
  },
  {
    id: 'nvidia/nemotron-nano-12b-v2-vl:free',
    name: 'nvidia/nemotron-nano-12b-v2-vl:free',
    displayName: 'Nemotron Nano 12B V2 VL (OpenRouter)',
    provider: 'openrouter',
    description: 'Nemotron Nano 12B V2 VL via OpenRouter',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: false,
  },
  {
    id: 'google/gemma-3-27b-it:free',
    name: 'google/gemma-3-27b-it:free',
    displayName: 'Gemma 3 27B IT (OpenRouter)',
    provider: 'openrouter',
    description: 'Gemma 3 27B IT via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: true,
  },
  {
    id: 'z-ai/glm-4.5-air:free',
    name: 'z-ai/glm-4.5-air:free',
    displayName: 'GLM 4.5 AIR (OpenRouter)',
    provider: 'openrouter',
    description: 'GLM 4.5 AIR via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: true,
  },
  {
    id: 'qwen/qwen3-coder:free',
    name: 'qwen/qwen3-coder:free',
    displayName: 'Qwen 3 Coder (OpenRouter)',
    provider: 'openrouter',
    description: 'Qwen 3 Coder via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: true,

  },
  {
    id: 'deepseek/deepseek-r1-0528:free',
    name: 'deepseek/deepseek-r1-0528:free',
    displayName: 'DeepSeek R1 0528 (OpenRouter)',
    provider: 'openrouter',
    description: 'DeepSeek R1 0528 via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: true,
  },
  {
    id: 'moonshotai/kimi-k2:free',
    name: 'moonshotai/kimi-k2:free',
    displayName: 'Kimi K2 (OpenRouter)',
    provider: 'openrouter',
    description: 'Kimi K2 via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'advanced-reasoning', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: true,
  },
  {
    id: 'google/gemma-3n-e4b-it:free',
    name: 'google/gemma-3n-e4b-it:free',
    displayName: 'Gemma 3N E4B IT (OpenRouter)',
    provider: 'openrouter',
    description: 'Gemma 3N E4B IT via OpenRouter',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.20,
    outputCost: 0.20,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: false,
    capabilities: ['text', 'images', 'audio', 'video', 'advanced-reasoning', 'code-generation'],
    contextWindow: 32768,
    isAvailable: true,
    temperature: 0.4,
    isReasoning: true,
  },
  
];
