import type { AIModel } from './types';

export const openaiModels: AIModel[] = [
  {
    id: 'gpt-4o',
    name: 'gpt-4o',
    displayName: 'GPT-4o',
    provider: 'openai',
    description: 'OpenAI\'s most advanced multimodal model',
    category: 'multimodal',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: true,
    supportsVideo: false,
    capabilities: ['text', 'images', 'audio', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'gpt-5-2025-08-07',
    name: 'gpt-5-2025-08-07',
    displayName: 'GPT-5 2025-08-07',
    provider: 'openai',
    description: 'OpenAI\'s latest model',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.8,
    isReasoning: false,
  },
  {
    id: 'gpt-5-mini-2025-08-07',
    name: 'gpt-5-mini-2025-08-07',
    displayName: 'GPT-5 Mini 2025-08-07',
    provider: 'openai',
    description: 'OpenAI\'s latest model',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.8,
    isReasoning: false,
  },
  {
    id: 'gpt-5-nano-2025-08-07',
    name: 'gpt-5-nano-2025-08-07',
    displayName: 'GPT-5 Nano 2025-08-07',
    provider: 'openai',
    description: 'OpenAI\'s latest model',
    category: 'image-generation',
    maxTokens: 4096,
    inputCost: 5.00,
    outputCost: 15.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.8,
    isReasoning: false,
  },
  {
    id: 'gpt-4-turbo',
    name: 'gpt-4-turbo',
    displayName: 'GPT-4 Turbo',
    provider: 'openai',
    description: 'High-performance text and vision model',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 10.00,
    outputCost: 30.00,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'function-calling', 'advanced-reasoning'],
    contextWindow: 128000,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
];
