import type { AIModel } from './types';

export const xaiModels: AIModel[] = [
  {
    id: 'xai/grok-4',
    name: 'grok-4',
    displayName: 'Grok 4',
    provider: 'xai',
    description: 'xAI Grok 4 - Advanced reasoning model with 256K context window',
    category: 'reasoning',
    maxTokens: 4096,
    inputCost: 0.003,
    outputCost: 0.015,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation', 'advanced-reasoning'],
    contextWindow: 262144,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: true,
  },
  {
    id: 'xai/grok-2',
    name: 'grok-2',
    displayName: 'Grok 2',
    provider: 'xai',
    description: 'xAI Grok 2 model',
    category: 'text',
    maxTokens: 4096,
    inputCost: 0.003,
    outputCost: 0.015,
    supportsImages: false,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'code-generation'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
  {
    id: 'xai/grok-2-vision-1212',
    name: 'grok-2-vision-1212',
    displayName: 'Grok 2 Vision',
    provider: 'xai',
    description: 'xAI Grok 2 Vision model with image support',
    category: 'multimodal',
    maxTokens: 4096,
    inputCost: 0.003,
    outputCost: 0.015,
    supportsImages: true,
    supportsAudio: false,
    supportsVideo: false,
    capabilities: ['text', 'images', 'code-generation'],
    contextWindow: 131072,
    isAvailable: true,
    temperature: 0.7,
    isReasoning: false,
  },
];
