import {
    // Types used in other files might rely on namespace now
} from 'electron';

export interface IBaseWindow {
    // Properties
    readonly id: number;
    contentView: Electron.View;
    readonly tabbingIdentifier?: string;
    autoHideMenuBar: boolean;
    readonly simpleFullScreen: boolean;
    readonly fullScreen: boolean;
    readonly focusable: boolean;
    readonly visibleOnAllWorkspaces: boolean;
    readonly shadow: boolean;
    readonly menuBarVisible: boolean;
    readonly kiosk: boolean;
    documentEdited: boolean;
    representedFilename: string;
    title: string;
    readonly minimizable: boolean;
    readonly maximizable: boolean;
    readonly fullScreenable: boolean;
    readonly resizable: boolean;
    readonly closable: boolean;
    readonly movable: boolean;
    excludedFromShownWindowsMenu: boolean;
    readonly accessibleTitle: string;
    readonly snapped: boolean;

    // Instance Methods
    setContentView(view: Electron.View): void;
    getContentView(): Electron.View;
    destroy(): void;
    close(): void;
    focus(): void;
    blur(): void;
    isFocused(): boolean;
    isDestroyed(): boolean;
    show(): void;
    showInactive(): void;
    hide(): void;
    isVisible(): boolean;
    isModal(): boolean;
    maximize(): void;
    unmaximize(): void;
    isMaximized(): boolean;
    minimize(): void;
    restore(): void;
    isMinimized(): boolean;
    setFullScreen(flag: boolean): void;
    isFullScreen(): boolean;
    setSimpleFullScreen(flag: boolean): void;
    isSimpleFullScreen(): boolean;
    isNormal(): boolean;
    setAspectRatio(aspectRatio: number, extraSize?: Electron.Size): void;
    setBackgroundColor(backgroundColor: string): void;
    previewFile(path: string, displayName?: string): void;
    closeFilePreview(): void;
    setBounds(bounds: Partial<Electron.Rectangle>, animate?: boolean): void;
    getBounds(): Electron.Rectangle;
    getBackgroundColor(): string;
    setContentBounds(bounds: Electron.Rectangle, animate?: boolean): void;
    getContentBounds(): Electron.Rectangle;
    getNormalBounds(): Electron.Rectangle;
    setEnabled(enable: boolean): void;
    isEnabled(): boolean;
    setSize(width: number, height: number, animate?: boolean): void;
    getSize(): number[];
    setContentSize(width: number, height: number, animate?: boolean): void;
    getContentSize(): number[];
    setMinimumSize(width: number, height: number): void;
    getMinimumSize(): number[];
    setMaximumSize(width: number, height: number): void;
    getMaximumSize(): number[];
    setResizable(resizable: boolean): void;
    isResizable(): boolean;
    setMovable(movable: boolean): void;
    isMovable(): boolean;
    setMinimizable(minimizable: boolean): void;
    isMinimizable(): boolean;
    setMaximizable(maximizable: boolean): void;
    isMaximizable(): boolean;
    setFullScreenable(fullscreenable: boolean): void;
    isFullScreenable(): boolean;
    setClosable(closable: boolean): void;
    isClosable(): boolean;
    setHiddenInMissionControl(hidden: boolean): void;
    isHiddenInMissionControl(): boolean;
    setAlwaysOnTop(flag: boolean, level?: string, relativeLevel?: number): void;
    isAlwaysOnTop(): boolean;
    moveAbove(mediaSourceId: string): void;
    moveTop(): void;
    center(): void;
    setPosition(x: number, y: number, animate?: boolean): void;
    getPosition(): number[];
    setTitle(title: string): void;
    getTitle(): string;
    setSheetOffset(offsetY: number, offsetX?: number): void;
    flashFrame(flag: boolean): void;
    setSkipTaskbar(skip: boolean): void;
    setKiosk(flag: boolean): void;
    isKiosk(): boolean;
    isTabletMode(): boolean;
    getMediaSourceId(): string;
    getNativeWindowHandle(): Buffer;
    hookWindowMessage(message: number, callback: (wParam: Buffer, lParam: Buffer) => void): void;
    isWindowMessageHooked(message: number): boolean;
    unhookWindowMessage(message: number): void;
    unhookAllWindowMessages(): void;
    setRepresentedFilename(filename: string): void;
    getRepresentedFilename(): string;
    setDocumentEdited(edited: boolean): void;
    isDocumentEdited(): boolean;
    setMenu(menu: Electron.Menu | null): void;
    removeMenu(): void;
    setProgressBar(progress: number, options?: { mode: 'none' | 'normal' | 'indeterminate' | 'error' | 'paused' }): void;
    setOverlayIcon(overlay: Electron.NativeImage | null, description: string): void;
    invalidateShadow(): void;
    setHasShadow(hasShadow: boolean): void;
    hasShadow(): boolean;
    setOpacity(opacity: number): void;
    getOpacity(): number;
    setShape(rects: Electron.Rectangle[]): void;
    setThumbarButtons(buttons: Electron.ThumbarButton[]): boolean;
    setThumbnailClip(region: Electron.Rectangle): void;
    setThumbnailToolTip(toolTip: string): void;
    setAppDetails(options: { appId?: string; appIconPath?: string; appIconIndex?: number; relaunchCommand?: string; relaunchDisplayName?: string }): void;
    setAccentColor(accentColor: boolean | string | null): void;
    getAccentColor(): string | boolean;
    setIcon(icon: Electron.NativeImage | string): void;
    setWindowButtonVisibility(visible: boolean): void;
    setAutoHideMenuBar(hide: boolean): void;
    isMenuBarAutoHide(): boolean;
    setMenuBarVisibility(visible: boolean): void;
    isMenuBarVisible(): boolean;
    isSnapped(): boolean;
    setVisibleOnAllWorkspaces(visible: boolean, options?: { visibleOnFullScreen?: boolean; skipTransformProcessType?: boolean }): void;
    isVisibleOnAllWorkspaces(): boolean;
    setIgnoreMouseEvents(ignore: boolean, options?: { forward?: boolean }): void;
    setContentProtection(enable: boolean): void;
    isContentProtected(): boolean;
    setFocusable(focusable: boolean): void;
    isFocusable(): boolean;
    setParentWindow(parent: IBaseWindow | null): void;
    getParentWindow(): IBaseWindow | null;
    getChildWindows(): IBaseWindow[];
    setAutoHideCursor(autoHide: boolean): void;
    selectPreviousTab(): void;
    selectNextTab(): void;
    showAllTabs(): void;
    mergeAllWindows(): void;
    moveTabToNewWindow(): void;
    toggleTabBar(): void;
    addTabbedWindow(baseWindow: IBaseWindow): void;
    setVibrancy(type: string | null): void;
    setBackgroundMaterial(material: 'auto' | 'none' | 'mica' | 'acrylic' | 'tabbed'): void;
    setWindowButtonPosition(position: Electron.Point | null): void;
    getWindowButtonPosition(): Electron.Point | null;
    setTouchBar(touchBar: Electron.TouchBar | null): void;
    setTitleBarOverlay(options: { color?: string; symbolColor?: string; height?: number }): void;

    // Event Emitter methods
    on(event: string, listener: Function): void;
    once(event: string, listener: Function): void;
    removeListener(event: string, listener: Function): void;
    removeAllListeners(event?: string): void;
}

export interface IBaseWindowFactory {
    create(options?: Electron.BaseWindowConstructorOptions): IBaseWindow;
    getAllWindows(): IBaseWindow[];
    getFocusedWindow(): IBaseWindow | null;
    fromId(id: number): IBaseWindow | null;
}
