/**
 * YouTube Transcript API
 * 
 * Clean, simple API for extracting YouTube transcripts.
 * This is the main interface for integrating transcript features.
 * 
 * @example
 * ```typescript
 * import { YouTubeTranscriptAPI } from './youtube-transcript';
 * 
 * // Simple usage
 * const transcript = await YouTubeTranscriptAPI.getTranscript('VIDEO_URL');
 * 
 * // With options
 * const transcript = await YouTubeTranscriptAPI.getTranscript('VIDEO_URL', {
 *   includeTimestamps: true,
 *   language: 'en'
 * });
 * ```
 */

import { TranscriptService, transcriptService } from '../services';
import {
  TranscriptResult,
  TranscriptSuccessResult,
  TranscriptErrorResult,
  ValidationResult,
  LanguageInfo,
  VideoId,
} from '../types';

// ============================================================================
// API Types
// ============================================================================

/**
 * Options for fetching transcript
 */
export interface TranscriptAPIOptions {
  /** Include timestamps in the transcript text */
  includeTimestamps?: boolean;
  /** Preferred language code (e.g., 'en', 'es', 'fr') */
  language?: string;
}

/**
 * Transcript data returned by the API
 */
export interface TranscriptData {
  /** The transcript text */
  text: string;
  /** Video ID */
  videoId: string;
  /** Language information */
  language: {
    code: string;
    name: string;
    isAutoGenerated: boolean;
  };
  /** Available languages for this video */
  availableLanguages: LanguageInfo[];
  /** Number of caption tracks */
  trackCount: number;
}

/**
 * API Response wrapper
 */
export interface APIResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
}

// ============================================================================
// YouTube Transcript API
// ============================================================================

/**
 * YouTubeTranscriptAPI - Main API class for transcript extraction
 * 
 * Provides static methods for easy access without instantiation.
 */
export class YouTubeTranscriptAPI {
  private static service: TranscriptService = transcriptService;

  /**
   * Get transcript for a YouTube video
   * 
   * @param urlOrVideoId - YouTube URL or video ID
   * @param options - Optional settings
   * @returns Transcript data or error
   * 
   * @example
   * ```typescript
   * const result = await YouTubeTranscriptAPI.getTranscript('dQw4w9WgXcQ');
   * if (result.success) {
   *   console.log(result.data.text);
   * }
   * ```
   */
  static async getTranscript(
    urlOrVideoId: string,
    options: TranscriptAPIOptions = {}
  ): Promise<APIResponse<TranscriptData>> {
    const result = await this.service.getTranscript(urlOrVideoId, {
      includeTimestamps: options.includeTimestamps ?? false,
      languageCode: options.language,
    });

    if (result.success) {
      const successResult = result as TranscriptSuccessResult;
      return {
        success: true,
        data: {
          text: successResult.transcript,
          videoId: successResult.videoId,
          language: {
            code: successResult.language.code,
            name: successResult.language.name,
            isAutoGenerated: successResult.language.kind === 'asr',
          },
          availableLanguages: successResult.availableLanguages,
          trackCount: successResult.metadata.trackCount,
        },
      };
    }

    return {
      success: false,
      error: (result as TranscriptErrorResult).error,
    };
  }

  /**
   * Get just the transcript text (convenience method)
   * 
   * @param urlOrVideoId - YouTube URL or video ID
   * @param options - Optional settings
   * @returns Transcript text or null
   * 
   * @example
   * ```typescript
   * const text = await YouTubeTranscriptAPI.getText('dQw4w9WgXcQ');
   * if (text) {
   *   console.log(text);
   * }
   * ```
   */
  static async getText(
    urlOrVideoId: string,
    options: TranscriptAPIOptions = {}
  ): Promise<string | null> {
    const result = await this.getTranscript(urlOrVideoId, options);
    return result.success ? result.data!.text : null;
  }

  /**
   * Get available caption languages for a video
   * 
   * @param urlOrVideoId - YouTube URL or video ID
   * @returns Available languages or error
   * 
   * @example
   * ```typescript
   * const result = await YouTubeTranscriptAPI.getLanguages('dQw4w9WgXcQ');
   * if (result.success) {
   *   result.data.forEach(lang => console.log(lang.name));
   * }
   * ```
   */
  static async getLanguages(
    urlOrVideoId: string
  ): Promise<APIResponse<LanguageInfo[]>> {
    const result = await this.service.getAvailableLanguages(urlOrVideoId);

    if (result.success) {
      return {
        success: true,
        data: result.languages || [],
      };
    }

    return {
      success: false,
      error: result.error,
    };
  }

  /**
   * Check if a video has captions available
   * 
   * @param urlOrVideoId - YouTube URL or video ID
   * @returns True if captions are available
   * 
   * @example
   * ```typescript
   * if (await YouTubeTranscriptAPI.hasCaptions('dQw4w9WgXcQ')) {
   *   // Fetch transcript
   * }
   * ```
   */
  static async hasCaptions(urlOrVideoId: string): Promise<boolean> {
    const result = await this.getLanguages(urlOrVideoId);
    return result.success && (result.data?.length ?? 0) > 0;
  }

  /**
   * Validate a YouTube URL or video ID
   * 
   * @param urlOrVideoId - URL or video ID to validate
   * @returns Validation result with extracted video ID
   * 
   * @example
   * ```typescript
   * const result = YouTubeTranscriptAPI.validate('https://youtube.com/watch?v=dQw4w9WgXcQ');
   * if (result.valid) {
   *   console.log('Video ID:', result.videoId);
   * }
   * ```
   */
  static validate(urlOrVideoId: string): ValidationResult {
    return this.service.validateUrl(urlOrVideoId);
  }

  /**
   * Extract video ID from URL
   * 
   * @param urlOrVideoId - YouTube URL or video ID
   * @returns Video ID or null
   * 
   * @example
   * ```typescript
   * const videoId = YouTubeTranscriptAPI.extractVideoId('https://youtu.be/dQw4w9WgXcQ');
   * // Returns: 'dQw4w9WgXcQ'
   * ```
   */
  static extractVideoId(urlOrVideoId: string): VideoId | null {
    const result = this.validate(urlOrVideoId);
    return result.videoId;
  }

  /**
   * Get transcript with full metadata (raw result)
   * 
   * @param urlOrVideoId - YouTube URL or video ID
   * @param options - Optional settings
   * @returns Full transcript result from service
   */
  static async getRawTranscript(
    urlOrVideoId: string,
    options: TranscriptAPIOptions = {}
  ): Promise<TranscriptResult> {
    return this.service.getTranscript(urlOrVideoId, {
      includeTimestamps: options.includeTimestamps ?? false,
      languageCode: options.language,
    });
  }
}

// ============================================================================
// Functional API (Alternative to class-based API)
// ============================================================================

/**
 * Get transcript for a YouTube video
 * Functional alternative to YouTubeTranscriptAPI.getTranscript()
 */
export async function getTranscript(
  urlOrVideoId: string,
  options: TranscriptAPIOptions = {}
): Promise<APIResponse<TranscriptData>> {
  return YouTubeTranscriptAPI.getTranscript(urlOrVideoId, options);
}

/**
 * Get just the transcript text
 * Functional alternative to YouTubeTranscriptAPI.getText()
 */
export async function getTranscriptText(
  urlOrVideoId: string,
  options: TranscriptAPIOptions = {}
): Promise<string | null> {
  return YouTubeTranscriptAPI.getText(urlOrVideoId, options);
}

/**
 * Get available languages for a video
 * Functional alternative to YouTubeTranscriptAPI.getLanguages()
 */
export async function getAvailableLanguages(
  urlOrVideoId: string
): Promise<APIResponse<LanguageInfo[]>> {
  return YouTubeTranscriptAPI.getLanguages(urlOrVideoId);
}

/**
 * Check if a video has captions
 * Functional alternative to YouTubeTranscriptAPI.hasCaptions()
 */
export async function hasCaptions(urlOrVideoId: string): Promise<boolean> {
  return YouTubeTranscriptAPI.hasCaptions(urlOrVideoId);
}

/**
 * Validate YouTube URL or video ID
 * Functional alternative to YouTubeTranscriptAPI.validate()
 */
export function validateUrl(urlOrVideoId: string): ValidationResult {
  return YouTubeTranscriptAPI.validate(urlOrVideoId);
}

/**
 * Extract video ID from URL
 * Functional alternative to YouTubeTranscriptAPI.extractVideoId()
 */
export function extractVideoId(urlOrVideoId: string): VideoId | null {
  return YouTubeTranscriptAPI.extractVideoId(urlOrVideoId);
}
