/**
 * API Test - Demonstrates the YouTube Transcript API usage
 * 
 * Run with: npx ts-node src/__tests__/api-test.ts [URL]
 */

import { 
  YouTubeTranscriptAPI,
  getTranscriptText,
  hasCaptions,
} from '../index';

const DEFAULT_VIDEO_URL = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';

async function main(): Promise<void> {
  const url = process.argv[2] || DEFAULT_VIDEO_URL;

  console.log('='.repeat(60));
  console.log('YouTube Transcript API Test');
  console.log('='.repeat(60));

  // 1. Validate URL
  console.log('\n📋 Validating URL...');
  const validation = YouTubeTranscriptAPI.validate(url);
  console.log(`   Valid: ${validation.valid}`);
  console.log(`   Video ID: ${validation.videoId}`);

  if (!validation.valid) {
    console.error(`❌ Invalid URL: ${validation.error}`);
    process.exit(1);
  }

  // 2. Check if captions exist
  console.log('\n🔍 Checking for captions...');
  const captionsExist = await hasCaptions(url);
  console.log(`   Has captions: ${captionsExist}`);

  if (!captionsExist) {
    console.error('❌ No captions available for this video');
    process.exit(1);
  }

  // 3. Get available languages
  console.log('\n🌍 Available languages:');
  const languages = await YouTubeTranscriptAPI.getLanguages(url);
  if (languages.success && languages.data) {
    languages.data.forEach(lang => {
      const type = lang.kind === 'asr' ? '(auto)' : '(manual)';
      console.log(`   - ${lang.name} [${lang.languageCode}] ${type}`);
    });
  }

  // 4. Get transcript using class API
  console.log('\n📝 Fetching transcript (Class API)...');
  const result = await YouTubeTranscriptAPI.getTranscript(url);
  
  if (result.success && result.data) {
    console.log(`   ✅ Success!`);
    console.log(`   Language: ${result.data.language.name}`);
    console.log(`   Auto-generated: ${result.data.language.isAutoGenerated}`);
    console.log(`   Length: ${result.data.text.length} chars`);
    console.log(`\n   Preview (first 300 chars):`);
    console.log(`   ${result.data.text.substring(0, 300)}...`);
  } else {
    console.error(`   ❌ Failed: ${result.error}`);
  }

  // 5. Get transcript using functional API
  console.log('\n\n📝 Fetching transcript (Functional API)...');
  const text = await getTranscriptText(url);
  
  if (text) {
    console.log(`   ✅ Got ${text.length} characters`);
  } else {
    console.error('   ❌ Failed to get transcript');
  }

  console.log('\n' + '='.repeat(60));
  console.log('✅ API Test Complete!');
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});
