// DOM element getters to avoid direct global lookups in modules
export const dom = {
    get messageInput() { return document.getElementById('messageInput'); },
    get sendButton() { return document.getElementById('sendButton'); },
    get expandButton() { return document.getElementById('expandButton'); },
    get collapseButton() { return document.getElementById('collapseButton'); },
    get sendIcon() { return document.getElementById('sendIcon'); },
    get loadingSpinner() { return document.getElementById('loadingSpinner'); },
    get typingIndicator() { return document.getElementById('typingIndicator'); },
    get uploadButton() { return document.getElementById('uploadButton'); },
    get captureButton() { return document.getElementById('captureButton'); },
    get lightingButton() { return document.getElementById('lightingButton'); },
    get themeToggleButton() { return document.getElementById('themeToggleButton'); },
    get hideShowButton() { return document.getElementById('hideShowButton'); },
    get autoPasteToggleButton() { return document.getElementById('autoPasteToggleButton'); },
    get promptInput() { return document.querySelector('.prompt-input'); },
    get dragHandle() { return document.querySelector('.drag-handle'); },
    get promptActions() { return document.querySelector('.prompt-actions'); },
    get leftActions() { return document.querySelector('.left-actions'); },
    get rightActions() { return document.querySelector('.right-actions'); },
    get draggableArea() { return document.querySelector('.draggable-area'); },
    get uploadDropdown() { return document.getElementById('uploadDropdown'); },
    get captureDropdown() { return document.getElementById('captureDropdown'); },
    get modelSelectButton() { return document.getElementById('modelSelectButton'); },
    get modelSelectDropdown() { return document.getElementById('modelSelectDropdown'); },
    get newChatButton() { return document.getElementById('newChatButton'); },
    get chatInputContainer() { return document.querySelector('.chat-input-container'); },
    get contentProtectionButton() { return document.getElementById('contentProtectionButton'); },
    get plusButton() { return document.getElementById('plusButton'); },
    get expandedPlusButton() { return document.getElementById('expandedPlusButton'); },
    get plusActionsDropdown() { return document.getElementById('plusActionsDropdown'); },
    get attachmentsContainer() { return document.getElementById('attachmentsContainer'); },
    get attachmentsSection() { return document.getElementById('attachmentsSection'); },
    get attachmentsGrid() { return document.getElementById('attachmentsGrid'); },
    get clearAllButton() { return document.getElementById('clearAllAttachments'); },
    get clickThroughButton() { return document.getElementById('clickThroughButton'); },
    get hideChatButton() { return document.getElementById('hideChatButton'); },
    get badgesContainer() { return document.getElementById('badgesContainer'); },
    get badgesGrid() { return document.getElementById('badgesGrid'); },
    get networkWarning() { return document.getElementById('networkWarning'); },
};


